/** Every tuning constant for Alpine Rush lives here, grouped by system, so feel can be changed in one place. */
export const CONFIG = {
  seed: 1337,

  visual: {
    skyTop: 0x2e6fd1,
    skyHorizon: 0xbfdbf7,
    sunHalo: 0xfff2d0,
    snowColor: 0xf2f6ff,
    snowShadowTint: 0xaecbec,
    jacketColor: 0xe8552d,
    helmetColor: 0xf4b93d,
    goggleColor: 0x3a6ea8,
    pineColor: 0x1f4d33,
    fogColor: 0xc9ddf2,
    fogDensity: 0.0025,
    exposure: 1.05,
    maxPixelRatio: 1.5,
  },

  spline: {
    controlSpacing: 30,
    lateralWavelengthMin: 150,
    lateralWavelengthMax: 220,
    lateralAmplitudeMin: 25,
    lateralAmplitudeMax: 40,
    lateralRerollChance: 0.1,
    gradeMainMinDeg: 12,
    gradeMainMaxDeg: 18,
    gradeFlatDeg: 7.5,
    gradeSteepDeg: 23,
    gradeFlatChance: 0.12,
    gradeSteepChance: 0.12,
    gradeHoldMin: 5,
    gradeHoldMax: 14,
  },

  terrain: {
    corridorHalfWidth: 24,
    pisteHalfWidth: 18,
    rollerShortWavelength: 14,
    rollerShortAmp: 0.35,
    rollerLongWavelength: 140,
    rollerLongAmp: 1.6,
    mogulScale: 3.2,
    mogulAmp: 0.55,
    kickerChanceMax: 2,
    kickerUpSigmaMin: 8.5,
    kickerUpSigmaMax: 11.5,
    kickerDownSigmaMin: 2.7,
    kickerDownSigmaMax: 3.6,
    kickerAmpMin: 1.15,
    kickerAmpMax: 2.3,
    kickerLateralOffsetMax: 9,
    kickerStartChunk: 2,
  },

  chunk: {
    length: 100,
    ahead: 8,
    behind: 2,
    rows: 64,
    denseSpacing: 1.65,
    sparseSpacing: 6.5,
    denseHalfWidth: 33,
    outerHalfWidth: 70,
    lodFullDistance: 190,
    lodMediumDistance: 430,
    aoRadius: 6,
    aoStrength: 0.55,
  },

  decor: {
    treeNearDensity: 0.3,
    treeFarDensity: 0.8,
    treeVariants: 3,
    treeScaleMin: 0.95,
    treeScaleMax: 1.8,
    treeMaxTilt: 0.12,
    heroTreeChance: 0.12,
    rockOutcropChance: 0.35,
    logChance: 0.08,
    bushChance: 0.5,
    obstacleStartChunk: 3,
    obstacleMaxPerChunk: 4,
    obstacleRockChance: 0.25,
  },

  pickups: {
    orbColor: 0x4fd8ff,
    orbPoints: 50,
    orbCount: {
      line: 8,
      arc: 9,
      zigzag: 10,
    },
    zigzagOffset: 9,
    boostChance: 0.3,
    boostDuration: 3,
    boostAccel: 14,
    boostFovKick: 6,
    shieldChance: 0.1,
    magnetRadius: 3,
    collectRadius: 1.3,
  },

  gates: {
    chance: 0.45,
    count: 3,
    spacing: 32,
    lateralOffset: 6,
    poleGap: 7,
    scorePass: 250,
    passRadius: 3.5,
    missRadius: 16,
  },

  physics: {
    gravity: 9.81,
    maxEdgeAngle: Math.PI / 4,
    edgeEase: 4.2,
    gripDrifty: 1.8,
    gripCarving: 9.5,
    yawEdgeGain: 2.35,
    yawSpeedFull: 7,
    lateralAccelCapBase: 44,
    corridorAssistInner: 12,
    corridorAssistOuter: 24,
    friction: 0.34,
    drag: 0.0034,
    tuckDragFactor: 0.65,
    carveSpeedScrub: 0.55,
    maxSpeed: 42,
    speedRampDistance: 4000,
    speedRampImprovement: 0.35,
    floorSpeedStart: 13,
    floorSpeedEnd: 33,
    floorRampDistance: 3500,
    boundaryDistance: 21,
    boundaryPushStrength: 6,
    stallSpeed: 3.5,
    stallTime: 2.2,
    respawnCollisionGrace: 1.2,
  },

  air: {
    takeoffDropThreshold: 2.6,
    takeoffKeepFraction: 0.35,
    jumpImpulse: 4.9,
    airTurnRate: 1.15,
    spinRate: (720 * Math.PI) / 180,
    spinRampTime: 0.25,
    cleanLandingToleranceDeg: 30,
    switchLandingToleranceDeg: 130,
    bigAirTime: 1.15,
    wipeoutTumbleTime: 1.5,
    wipeoutSpinFactor: 0.4,
  },

  scoring: {
    spinPer180: 150,
    grabScore: 120,
    bigAirScore: 100,
    switchScore: 80,
    comboWindow: 6,
    comboPerChain: 0.25,
    comboMax: 8,
  },

  camera: {
    stiffness: 6,
    damping: 0.85,
    heightOffset: 3.9,
    followDistance: 9.2,
    leash: 5,
    minHeightAboveTerrain: 1.35,
    lookAheadRider: 6.5,
    lookAheadSpline: 12,
    lookAheadSplineBlend: 0.25,
    maxRollDeg: 5.2,
    fovMin: 70,
    fovMax: 85,
  },

  snow: {
    grooveFrequency: 17,
    roughness: 0.94,
    glitterSpecularPower: 118,
    glitterGate: 0.98,
    glitterBoost: 3.5,
    wrapFillStrength: 0.35,
  },

  effects: {
    trailSegments: 320,
    trailMinSpeed: 5,
    trailLifetime: 6,
    sprayPoolSize: 400,
    powderPoolSize: 200,
    shockwavePoolSize: 10,
    snowflakeCount: 2000,
    snowBoxSize: { x: 80, y: 40, z: 100 },
  },

  scenery: {
    ridgeLayers: [
      { distance: 900, followFactor: 0.93, height: 220 },
      { distance: 1400, followFactor: 0.88, height: 340 },
    ],
    cloudCount: 4,
    sunElevationDeg: 18,
    sunIntensity: 3.2,
    shadowMapDesktop: 4096,
    shadowMapMobile: 2048,
    shadowBoxSize: 62,
  },

  post: {
    bloomThreshold: 0.82,
    bloomStrength: 0.55,
    bloomRadius: 0.4,
    dofNearStart: 45,
    dofNearRange: 130,
    chromaticAberrationBase: 0.0015,
    chromaticAberrationImpact: 0.01,
    vignetteStrength: 0.35,
    grainStrength: 0.03,
    filmicContrast: 1.12,
    filmicSaturation: 1.08,
    speedStreakThreshold: 32,
  },

  adaptive: {
    frameTimeTargetMs: 16.7,
    frameTimeStepDownMs: 19.5,
    emaAlpha: 0.08,
    pixelRatioStep1: 1.12,
  },

  mobile: {
    steerZoneFraction: 0.4,
    pixelRatio: 1.25,
  },

  hud: {
    speedDisplayScale: 3.6,
  },
} as const;

export type Config = typeof CONFIG;
